### ISSUE TITLE
part1&part2，程序启动后没有回应

### ISSUE THREAD

**Issue by JackVictor1027** [youngyangyang04/RPC-Java#12]
先生你好，我现在进展到项目的part2，在此之前和现在，我都很多次的debug和重启客户端/服务端，但是客户端发出去的请求都没有得到服务端的任何响应，就如图1和图2所示。
经过排查，我发现客户端在获取代理对象时，运行模式下程序长时间地遭遇阻塞（debug模式下则长时间显示“正在收集数据”）。我一直尝试在网络上找寻答案，但都没有得到理想的解决方案。请问您知道其中的原因和解决方法吗？打扰了！
**图1**
![PixPin_2024-07-18_21-36-33](https://github.com/user-attachments/assets/4d5d0b5a-c546-432d-8f53-c3bb0fae62b5)
**图2**
![PixPin_2024-07-18_21-36-46](https://github.com/user-attachments/assets/091acd4d-f600-4c6f-a6ed-1db8aa9d6d8b)
**图3**
![PixPin_2024-07-18_21-48-52](https://github.com/user-attachments/assets/56445778-0cdf-421a-8932-26d57651761e)

**Comment by GGBoooond** [comment]
端口被占用是有可能导致堵塞的；
但是你debug堵在getProxy这里，没太明白。。类加载器获取不到？看一下配置啥的，，，

**Comment by JackVictor1027** [comment]
你好，应该是我没有表述明白。刚才我又debug，问题可以基本集中在getProxy方法这里——每当客户端尝试获取代理时，都无法正常获取，抛出下图所示的异常，可能的原因有哪些呢？
感谢你于百忙之中回答我的问题
 



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月20日 22:49 |
| 收件人 | ***@***.***> |
| 抄送人 | Jack ***@***.***>,
***@***.***> |
| 主题 | Re: [youngyangyang04/RPC-Java] part1&part2，程序启动后没有回应 (Issue #12) |

端口被占用是有可能导致堵塞的；
但是你debug堵在getProxy这里，没太明白。。类加载器获取不到？看一下配置啥的，，，

**Comment by GGBoooond** [comment]
我觉得是java的配置问题，重新配置一下；可以先写一个动态代理的demo，看看是否能获取到代理对象

**Comment by JackVictor1027** [comment]
我查阅了一些资料，也问了GPT，最终解决了问题——问题出在我的InvocationHandler实现类ClientProxy没有完善对toString(),hashCode(),equals()这些基础方法的重写，当我在invoke方法通过反射获取方法名后，我写出了这三个方法分别对应的实现，再进行调试，终于解决了问题。
![image](https://github.com/user-attachments/assets/d9944ce9-6910-4cf0-9a9c-c6e1a73d5459)
